InseadBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: InseadBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }

    manyToMany:
        Ads:
            targetEntity: InseadBundle\Entity\Ad
            inversedBy: users
