<?php

namespace InseadBundle\Repository;

/**
 * ChoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoicesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getChoicesById($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->join('c.questions', 'q')
            ->where('q.id = :id')
            ->setParameter('id', $id);
        return $qb;
    }
}
