<?php

namespace InseadBundle\Repository;

/**
 * QuestionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionsRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindOneBy($id){
        $qb = $this->createQueryBuilder('questions');
        $qb->select('questions')
            ->where('questions.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getSingleResult();
    }
}